# ビルドステージ
FROM node:lts as build-stage
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci --only=production
COPY ./frontend/ ./
RUN npm run build

# 実行ステージ
FROM nginx:stable-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
