version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: express-container
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    command: npm run dev
    volumes:
      - ./backend:/app/
      - /app/node_modules
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    container_name: react-container-prod
    volumes:
      - /app/node_modules
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80" # HTTPSを使用する場合は443も設定
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
    # HTTPSを使用する場合は、SSL証明書関連のボリュームもマウントする