services:

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: react-container
    volumes:
      - ./frontend:/app # ローカルのfrontendディレクトリをコンテナの/appディレクトリにマウント
      - /app/node_modules # node_modulesはコンテナ内に保持する
    command: sh -c "PORT=3000 npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: fastapi-container
    volumes:
      - ./backend:/app # ローカルのbackendディレクトリをコンテナの/appディレクトリにマウント
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
